[tool.poetry]
name = "bento-tools"
packages = [
  {include = "bento"},
]
version = "0.1.0"
description = "A toolkit for subcellular analysis of RNA organization"
authors = ["Clarence Mah <ckmah@ucsd.edu>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8"
anndata = "^0.7"
astropy = "^4.0.1"
geopandas = "^0.9.0"
ipywidgets = "^7.5.1"
leidenalg = "^0.8.3"
matplotlib = "^3.2.1"
numpy = "^1.18.4"
pandas = "^1.2"
proplot = "^0.7.0"
pygeos = "^0.8"
rasterio = "^1.2.6"
seaborn = "^0.11.0"
scanpy = "^1.6.0"
scipy = "^1.4.1"
Shapely = "^1.7.0"
skorch = "^0.9.0"
torchvision = "^0.8.1"
tqdm = "^4.44"
umap-learn = "^0.3.10"
datashader = "^0.12.0"

[tool.poetry.dev-dependencies]
Sphinx = "^4.1.2"
pydata-sphinx-theme = "^0.6.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
