[tool.poetry]
name = "bento-tools"
packages = [{ include = "bento" }]
include = ["bento/datasets/datasets.csv", "bento/models/**/*"]
version = "0.1.1"
description = "A toolkit for subcellular analysis of RNA organization"
authors = ["Clarence Mah <ckmah@ucsd.edu>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<3.10"
anndata = "^0.7.6"
astropy = "^4.3.post1"
geopandas = "^0.9.0"
ipywidgets = "^7.6.3"
leidenalg = "^0.8.7"
matplotlib = "^3.4.2"
numpy = "^1.19.0"
pandas = "^1.3.1"
proplot = "^0.7.0"
pygeos = "^0.10.1"
rasterio = "^1.2.6"
seaborn = "^0.11.1"
scipy = "^1.7.0"
Shapely = "^1.7.1"
skorch = "^0.10.0"
torchvision = "^0.10.0"
tqdm = "^4.61.2"
umap-learn = "^0.5.1"
datashader = "^0.13.0"

# make these main dependencies for now [tool.poetry.dev-dependencies]
Sphinx = "^4.1.2"
pydata-sphinx-theme = "^0.6.3"
statsmodels = "0.12.2"

[build-system]
requires = ["poetry-core>=1.0.0", 'setuptools']
build-backend = "poetry.core.masonry.api"
